follow: add <summary> as a clickable element
luakit/luakit pull request #1089
Opened 2024-09-15 16:49 UTC by balejk

Clicking this element will toggle the visibility of the content of the
containing <details> element.

2024-09-16 20:20 UTC, msdemlei requested changes
Thanks for this contribution!

I think having summary keyboard-operatable is right.  However, I had to look it up, too: The idea is that you toggle the visibility of an associated details in this way.

Perhaps you can state about as much in the commit message? Other than that I'd say let's go.

2024-09-16 20:20 UTC, msdemlei commented on CHANGELOG.md
> +- The `<summary>` element to clickable selectors in the `follow` plugin.
This is not quite a proper sentence.  Suggestion: "summary elements can to be operated through f hints, too".

2024-09-17 20:42 UTC, balejk commented
> I think having summary keyboard-operatable is right.  However, I had to look it up, too: The idea is that you toggle the visibility of an associated details in this way.
>
> Perhaps you can state about as much in the commit message? Other than that I'd say let's go.

I'm confused, isn't that exactly what I wrote there?

> > @@ -6,6 +6,7 @@
>  
>  - Manage dom events with luakit signals.
>  - An enable_pdfjs setting to go back to letting viewpdf handle PDFs.
> +- The `<summary>` element to clickable selectors in the `follow` plugin.
>
> This is not quite a proper sentence.  Suggestion: "summary elements can to be operated through f hints, too".

Well, I followed your precendence a line above :-) But if you still
think it should be changed, I can certainly reword it. How about
"<summary> elements are now hinted as clickable."?

Thank you for your feedback!

2024-09-18 06:50 UTC, msdemlei commented
On Tue, Sep 17, 2024 at 01:42:29PM -0700, balejk wrote:
> > I think having summary keyboard-operatable is right.  However, I had to look it up, too: The idea is that you toggle the visibility of an associated details in this way.
> >
> > Perhaps you can state about as much in the commit message? Other than that I'd say let's go.
>
> I'm confused, isn't that exactly what I wrote there?

You did, sorry, it was me who was confused.

> > This is not quite a proper sentence.  Suggestion: "summary elements can to be operated through f hints, too".
>
> Well, I followed your precendence a line above :-) But if you still
> think it should be changed, I can certainly reword it. How about
> "<summary> elements are now hinted as clickable."?

That's great.  Let's go for it (ideally with a commit --amend and a
push -f).  And yes, I notice my changelog entry was not a good
sentence either.  Should be fixed before the next release, sure.

Thanks!

2024-09-18 07:59 UTC, balejk commented
I have pushed the change.

2024-09-18 17:52 UTC, c0dev0id commented
Looks good. I'll merge it. Thanks!

2024-09-18 17:52 UTC, merged