partial replacement for jquery
luakit/luakit pull request #438
Opened 2017-08-13 11:25 UTC by szbnwer

needs testing

a <span> with "clickable" class (for the appearance, but maybe as well for the js - so iterate them, and where data-filename appears, that can be made functional) (or a <button>) would be much better than using <a> tags
preventDefault and return false are not needed this way, but takes a deeper but easy modification...

custom attributes should have "data-" prefix for valid html5 - a search&replace can help for this

2017-08-13 11:43 UTC, szbnwer commented
so i don't know if open_editor works without line, but can be defaulted to 1

for iterating class lists i had problems with the for+in syntax previously, because these are virtual array-s or whatever, and they misbehaved, but that's probably task dependent...

the toggle works without animation

i have no associated text editor so i failed to test those, but the best method for that would be to iterate class="clickable" elements and where data-filename appears, those can be changed, where data-linedefined appears, there that can be used, or otherwise 1 for lineno if open_editor needs the 2nd argument (btw i'd prefer data-lineno or line or row or whatever instead of linedefined)

if you want it i can refine the code this way, but i'm not feeling the temptation currently to modify the whole source... but if you don't feel just as well, then later today maybe i can take some time for that :D

2017-08-13 11:47 UTC, aidanholm requested changes

2017-08-13 11:47 UTC, aidanholm commented on lib/introspector_chrome.lua
> +window.onload=function () {
Use `window.add_event_listener("load", ...)` instead

2017-08-13 11:47 UTC, aidanholm commented on lib/introspector_chrome.lua
> +    let bindClass = document.getElementsByClassName("bind");
Instead of performing separate queries to get all the elements, then iterating through them, add a single `click` event handler to `document.body`. Then check the clicked element `event.target` with `.matches(selector)` for each of the three selectors in the original code.

2017-08-13 11:47 UTC, aidanholm commented on lib/introspector_chrome.lua
> +            if (func_sourceStyle.display == "none") {
Use `element.classList.toggle('hidden')`; add a `.hidden` class to the stylesheet if it's not already there.

2017-08-13 11:48 UTC, aidanholm commented
It's worth noting that you don't have to bother making your JS cross-browser-compatible; you can use anything webkit supports

2017-08-13 12:05 UTC, szbnwer commented
i know :D but for+in is not about that and data- prefix is just for valid html5 that's never wrong :D

2017-08-13 12:12 UTC, aidanholm commented
Sorry, didn't see your second comment before.

No need to use a loop at all with the changes I requested. Toggle animation can be done with CSS. Using `data-` prefix is a good idea. You can use `line` instead of `linedefined` if you prefer. `open_editor`'s line number is optional.

2017-08-13 12:58 UTC, szbnwer commented
so what should i do and what should have done at all (those parts that i may or may not have enough time for...)

2017-08-13 13:13 UTC, aidanholm commented
First work on the requested changes; that's the important bit. If you have enough time you can do the other bits.

2017-08-13 15:45 UTC, szbnwer commented
i didn't get it where the datas comes from so i can't modify the classes...

window.add_event_listener("load", ...) - why this could be better?

.matches(selector) - i've never seen this, maybe doesn't even exists :D but o1===o2 can be good i think

where to add the .hidden? i mean introspector_chrome.lua or help_chrome.lua or the same with .html would be an unrelated generated doc right?

where can i find the contents of the page? i can't see in any file what i've seen on luakit://introspector... i dind't even really understood the codes :D and i've thought it will be kinda as fast as write what i've made and open an issue :D but fine i wanted the pain :) aand how to assign an editor, to become abled to test the stuffs?

i guess i'll make a simple .hidden {display: none} and let the css3 magic and data- prefixes for others or for myself later, but if not today, then much later, because it seems like i will have time and be online around thursday next time and i have to finish my work because testing will start on monday

and i've found a bug, that for example the F block on the introspector have long lines and they disappear in nowhere (i've got no scrollbars, i really didn't have enough time to make it a home sweet home... but a wrap: word-wrap or something like can solve that, but maybe i wrote wrong code, but should be something like this...)

so i don't know how much i'll do today if any, but hopefully this started as not urgent :D

2017-08-14 00:48 UTC, szbnwer commented
i've made some mess, because as i wanted to test it i just used an older version, but it's enough for today, it don't wanna work, but u can fix it if you won't wait for me... previously the toggle was working, but the editor with the original jquery didn't came, but instead of that the toggle was activated, this implementation should work i think - when it will work... btw i've found everything i was looking for previously :)

2017-08-14 01:57 UTC, aidanholm commented
No problem; I'll review it whenever it's ready. Glad you found everything :)

2017-08-14 04:44 UTC, aidanholm commented
Note that I won't be able to merge any changes against the old version of `help_chrome`; it has to be against a reasonably recent version.

2017-08-14 15:49 UTC, szbnwer commented
sure, i know, therefore i said the mistake to don't do :D

but i still have that hacky messed installation and i've got no automated installer that gets the new sauce, compiles and installs for a click, but i wanna do that 1st, and then i can put it from my test dir to my install dir (because i've putted it into Szoszi's dir, as probably i will reuse my functions in luakit when i will be more familiar with it...) however i have to refine a bit my basic install because it only used /usr/local/ as everything goes there from lua, luajit, lfs and tekui...

the current installation is from a previous sys as now everything works out of the box just with a folder that can be anywhere; installation works without privileges; it only needs the same architecture without reinstallation, and the installer needs sudo/root for a few packages (gcc, make, git, mercurial, libreadline6-dev, libncurses5-dev, libfreetype6-dev, libxft-dev, libxext-dev and libxxf86vm-dev) so things that are needed for a fresh raw debian but not after compiling :)

luakit with dev path can be replaced finely anywhere? (currently i modified prefix, therefore it became hacky and runs from the sauce folder with a bash script for cd + env varables :D ) and can luakit leave untouched folders like xdg /etc and whatever used by luakit, or can dev paths make those local what are there? - so what i wanna achieve is to put it in my folder and make it completely fs independent, and this way everything could work without privileges in home folder and can be moved anywhere (so  a poweruser toolset that works anywhere like on an unprivileged host or from a pendrive...) currently i have a supervisor for my app, that making it place independent by passing basedir and at the very beginning i'm rewriting package.path and package.cpath... i hope the same can be achieved in luakit via env variables...

and thx for any help! :)

2017-09-12 12:34 UTC, taiite commented
Hi @szbnwer!

I would like to help. :)
Are you still working on this? If so, which chrome pages have you already finished?

2017-09-13 02:35 UTC, aidanholm commented
Hey @taiite; as far as I know, @szbnwer has only worked on migrating the introspector page, and hasn't had time to begin work on any of the others. I know the history, downloads, and bookmarks pages all use jQuery at the moment, so any of those are up for grabs. No need to do all of them at once, either; one at a time is great too.

You'd need to open a separate PR of course. Also, see the review comments on this PR about the preferred ways of using standard JS functions like `add_event_listener`, `el.classList.toggle`, etc. Thanks! :)

2017-09-14 17:35 UTC, szbnwer commented
hi! :) fine thx! so i've messed with an older version in my pr, the toggle works but just hide/display instead of rolling, i couldn't associate a text editor, so that parts is questionable... check out the diff for changes, the js, maybe data- prefixes on the extra attributes and a removed extra html closing tag was all i've made iirc

now it seems that maybe i will have some more freedom but now there are a s#itload of incoming stuffs are waiting for me and some tasks here and there, after i've done with those and talked with my boss (this makes dependent my free time, but probably i've done there...)

2017-10-10 19:06 UTC, aidanholm commented
Closing, as jQuery has been removed already

2017-10-10 19:06 UTC, closed without merging