add a bind-match-failure warning to the window widget's hit method
luakit/luakit pull request #465
Opened 2017-08-24 15:54 UTC by gleachkr

Here's a first pass at closing #392

2017-08-24 15:59 UTC, aidanholm requested changes
That's a lot less code than I was expecting!

2017-08-24 15:59 UTC, aidanholm commented on lib/window.lua
> +            if w.buffer then oldbuf = w.buffer .. key else oldbuf = key end
Should probably be:
```lua
local oldbuf = (w.buffer or "") .. key
```

2017-08-24 15:59 UTC, aidanholm commented on lib/window.lua
> +            if not (newbuf or caught) and key:len() == 1 and w:is_mode("normal") then
What happens without the `w:is_mode("normal")` check? My concern is for things like `ex-follow` mode; pressing `;` followed by some random key wouldn't show anything in this case.

2017-08-24 15:59 UTC, aidanholm commented on lib/window.lua
> +                w:notify(oldbuf .. " is not a prefix of an existing binding")
This can probably just be "No binding matched..."

2017-08-24 16:10 UTC, gleachkr commented on lib/window.lua
> +            if not (newbuf or caught) and key:len() == 1 and w:is_mode("normal") then
It tends to spam the user with no-binding notifications in the non-normal modes, like insert or command. I thought it might be better to undernotify than overnotify. Maybe this should be configurable?

2017-08-24 16:11 UTC, gleachkr commented on lib/window.lua
> +                w:notify(oldbuf .. " is not a prefix of an existing binding")
How about `"No binding matched by "` .. oldbuf, so that you can tell if it's a typo?

2017-08-24 16:23 UTC, aidanholm commented on lib/window.lua
> +            if not (newbuf or caught) and key:len() == 1 and w:is_mode("normal") then
You could try moving it to the signal handler around line 169 of window.lua

2017-08-24 16:24 UTC, aidanholm commented on lib/window.lua
> +                w:notify(oldbuf .. " is not a prefix of an existing binding")
Good thinking, but s/by/for/

2017-08-26 21:49 UTC, gleachkr commented on lib/window.lua
> +            if not (newbuf or caught) and key:len() == 1 and w:is_mode("normal") then
Same problem there, I think, though I might not be seeing the idea you're seeing.

Also, I'm not sure in that context how to tell when a key is part of a prefix for a binding, and when it's not---it looks like you get `match` false when the keypress is part of a prefix, and just hasn't matched yet.

2017-08-27 14:30 UTC, gleachkr commented
Went ahead and applied those suggestions, also adding an option to make the modes in which the warning is triggered extensible (with default value `{"normal","ex-follow"}`.

2017-08-27 14:33 UTC, aidanholm commented
I actually don't think that's a good idea; ideally, it'd just work in _all_ modes. I'd say keep the whitelist private, which means no API break if this gets improved later.

2017-08-27 14:38 UTC, aidanholm commented
Instead of checking the current mode, you could check whether the input bar or the current view is focused; it's hacky, but it should work.

2017-08-27 14:47 UTC, gleachkr commented
Good idea. Still need a special case for insert mode, but seems to work otherwise. Added to latest commit.

2017-08-27 14:59 UTC, aidanholm requested changes

2017-08-27 14:59 UTC, aidanholm commented on lib/window.lua
> +
remove whitespace in this line

2017-08-27 14:59 UTC, aidanholm commented on lib/window.lua
> +            if not (newbuf or caught or w.ibar.input.focused or w:is_mode("insert")) and key:len() == 1 then
key can be a number, for mouse button bindings:
```
[    6.764182] E [core/common/lualib]: Lua error: attempt to index local 'key' (a number value)
                 Traceback:
                 (1) lib/window.lua:268 in function hit
                 (2) lib/webview.lua:82 in function [anonymous]
```

2017-08-27 15:03 UTC, aidanholm commented on lib/window.lua
> +                w:set_prompt()
With this, any notification will disappear if the user scrolls with the mousewheel, but clicks are ignored
I think scrolling with the mousewheel shouldn't dismiss the notice, and clicks should

2017-08-27 15:16 UTC, gleachkr commented on lib/window.lua
> +                w:set_prompt()
Yes, that seems reasonable. I don't have a scrollwheel right now. What keys does a scrollwheel send? or is there a better way of detecting scrollwheel events?

2017-08-27 15:17 UTC, gleachkr commented on lib/window.lua
> +            if not (newbuf or caught or w.ibar.input.focused or w:is_mode("insert")) and key:len() == 1 then
Right. Should there be a warning when no mouse button binding is matched (perhaps unless it's just a vanilla click), or should mouse events be ignored?

2017-08-27 15:20 UTC, aidanholm commented on lib/window.lua
> +                w:set_prompt()
If you have a touchpad, that works the same way. Scrolling is done with synthesized key events with `key = "Scroll"`: see `lib/webview.lua:88`

2017-08-27 15:21 UTC, aidanholm commented on lib/window.lua
> +            if not (newbuf or caught or w.ibar.input.focused or w:is_mode("insert")) and key:len() == 1 then
I think ignoring clicks is fine

2017-08-27 15:37 UTC, gleachkr commented
OK, updated.

2017-08-27 15:55 UTC, aidanholm requested changes
final code nit :)

2017-08-27 15:55 UTC, aidanholm commented on lib/window.lua
> +            elseif not (key == "Scroll") then
`key ~= "Scroll"`

2017-08-27 16:08 UTC, gleachkr commented
Great! Updated along with changelog.

2017-08-27 16:10 UTC, merged

2017-08-27 16:10 UTC, aidanholm commented
Merged :tada: Thanks :)