Add `tablist.always_visible` setting (#497)
luakit/luakit pull request #498
Opened 2017-09-01 19:31 UTC by hofheinz

2017-09-02 14:58 UTC, aidanholm requested changes
Thanks for the PR; looks good, but some minor changes are needed

2017-09-02 14:58 UTC, aidanholm commented on lib/lousy/widget/tablist.lua
> +        default = false,
This also needs `domain_specific = false,`

2017-09-02 14:58 UTC, aidanholm commented on lib/lousy/widget/tablist.lua
> +        end
I'd prefer that this be changed to set `tlist.widget.visible = true/false` instead; it's much clearer:
```lua
if settings.get_setting("tablist.always_visible") then
    tlist.widget.visible = true
else
    tlist.widget.visible = notebook:count() > 1
end
```

2017-09-02 14:58 UTC, aidanholm commented on lib/lousy/widget/tablist.lua
> +        end
Note that to be really robust, we need to call `update_tablist_visibility` when the `"tablist.always_visible"` setting changes, but I haven't added a `setting-changed` signal yet.

2017-09-02 14:58 UTC, aidanholm commented on lib/lousy/widget/tablist.lua
> +        if tlist.visible and (notebook:count() >= 2 or settings.tablist.always_visible) then
Don't use `settings.tablist.always_visible`; this is an API for the user, not for plugins. It won't return the default value, for example, and it's slower (not that that should matter much).

2017-09-03 10:49 UTC, hofheinz commented
Thank you for the code review and the constructive comments! I have updated the commit (and taken your version of the `update_tablist_visibility` method, works as expected). I agree with your remark about robustness (what if `tablist.always_visible` gets updated while one tab is open?). I could add a "todo" comment at the `update_tablist_visibility` method, and/or I can try to keep an eye on future commits (to see when the right signal has been added and change the method then).

Please allow one question about your version of `update_tablist_visibility`: you always set the `tlist.visible` property (to true or false), even if it already had that same value. In contrast, the previous code (not mine of course) went out of its way to only set `tlist.visible` if that changed its value (from true to false, or from false to true). Was there a reason for that? (Like: even changing from true to true triggers all kinds of then-unnecessary signals or such.)

2017-09-03 14:42 UTC, aidanholm commented
I'll probably add the code to listen for setting changes when that's finished; don't worry about it.

The way the old code worked was mostly just because of the way using method calls encourages a particular code style. It shouldn't have any performance impact, and if it does I'd consider that a bug in the widget implementation (which would be easy enough to fix).

2017-09-03 18:41 UTC, hofheinz commented
Thanks for the explanation!

2017-09-04 09:10 UTC, aidanholm commented
No worries, questions always welcome :)

2017-09-04 09:10 UTC, merged

2017-09-04 09:10 UTC, aidanholm commented
Thanks for the PR!