Make del_word in readline.lua UTF8-aware (fixes #525)
luakit/luakit pull request #541
Opened 2017-09-24 16:58 UTC by hofheinz

2017-09-25 18:54 UTC, hofheinz commented
This is a very crude attempt at a UTF8 library stub (only `utf8.len` and `utf8.offset` currently exist, but have the same interface as in Lua 5.3).

Most of the content is copied/pasted from other `common/clib/*.c` files, but my understanding of the Lua/C interaction is very limited. Hence, I guess there are still a number of problems (which I'd be happy to try to fix if made aware).

2017-09-26 04:17 UTC, aidanholm requested changes
This looks great! I only have a few minor comments; the biggest one is the class vs library issue

2017-09-26 04:17 UTC, aidanholm commented on common/clib/utf8.c
> +    lua_pushnumber(L, (ssize_t) g_utf8_strlen(NONULL(cmd), -1));
`NONULL` not necessary here; checkstring will always return a non-null pointer

2017-09-26 04:17 UTC, aidanholm commented on common/clib/utf8.c
> +luaH_utf8_len(lua_State *L)
`utf8.len` needs to support invalid strings: "If it finds any invalid byte sequence, returns a false value plus the position of the first invalid byte." You can use `g_utf8_validate` for this.

2017-09-26 04:17 UTC, aidanholm commented on common/clib/utf8.c
> +    const gint len = g_utf8_strlen(NONULL(cmd), -1);
Ditto re `NONULL`

2017-09-26 04:17 UTC, aidanholm commented on common/clib/utf8.c
> +        gchar *pos = g_utf8_offset_to_pointer(NONULL(cmd), widx - 1);
Ditto re `NONULL`

2017-09-26 04:17 UTC, aidanholm commented on common/clib/utf8.c
> +luaH_utf8_len(lua_State *L)
`utf8.len` also takes two optional integer arguments representing a byte slice of the string

2017-09-26 04:17 UTC, aidanholm commented on common/clib/utf8.c
> +utf8_class_setup(lua_State *L)
You've defined `utf8` as a class, which means that Lua code can create instances of it; it should be a library instead :)  See `clib/msg.c` for a minimal library to refer to.

2017-09-26 04:17 UTC, aidanholm commented on common/clib/utf8.c
> +luaH_utf8_offset(lua_State *L)
`utf8.offset` also takes an optional `i` parameter

2017-09-26 12:52 UTC, hofheinz commented
Thanks for the detailed review! (Sorry, I completely overlooked the parameters, and did not know any better than to make an instantiable class. Hopefully fixed. But, if I may say so, converting between 0-based [glib] and 1-based [lua] byte and UTF8 offsets really is a pain.)

2017-09-27 02:55 UTC, aidanholm requested changes

2017-09-27 02:55 UTC, aidanholm commented on common/clib/utf8.c
> +static lua_class_t utf8_class;
This isn't needed for a lib

2017-09-27 02:55 UTC, aidanholm commented on common/clib/utf8.c
> +lua_class_t *
ditto

2017-09-27 02:55 UTC, aidanholm commented on common/clib/utf8.c
> +    const gchar *str = luaL_checkstring(L, 1);
Use `luaL_checklstring()` instead of a separate `strlen()` call

2017-09-27 02:55 UTC, aidanholm commented on common/clib/utf8.c
> +    if(nargs > 1) {
Use `luaL_optinteger()`

2017-09-27 02:55 UTC, aidanholm commented on common/clib/utf8.c
> +luaH_utf8_convert_offset(ssize_t offset, ssize_t length) {
I'd prefer this be exactly compatible with Lua5.3: https://github.com/lua/lua/blob/b1daa069bac27055f17753e85dca6aa256efef6f/lutf8lib.c#L30

This means that `offset > length` is an error condition

2017-09-27 02:55 UTC, aidanholm commented on common/clib/utf8.c
> +    if(nargs > 2)
`luaL_optinteger`

2017-09-27 02:55 UTC, aidanholm commented on common/clib/utf8.c
> +    const gchar *str = luaL_checkstring(L, 1);
`luaL_checklstring`

2017-09-27 02:55 UTC, aidanholm commented on common/clib/utf8.c
> +    ssize_t widx = luaL_checkint(L, 2);
`luaL_checkinteger`

2017-09-27 02:55 UTC, aidanholm commented on common/clib/utf8.c
> +        lua_pushnumber(L, ret);
`lua_pushinteger`

2017-09-27 02:55 UTC, aidanholm commented on tests/async/test_clib_utf8.lua
> +    assert(utf8.len("")==0)
Test cases look good! But these should be using `assert.equal()`; first argument should be the number, e.g:
```
assert.equal(1, utf8.len("ä"))
```

2017-09-27 18:40 UTC, hofheinz commented
Thanks for the constructive comments! I tried to mimic Lua 5.3's
implementation better. There is one corner case that I find hard to imitate
(without introducing ugliness): `uf8.len("ä",1,1)` (intuitively, the UTF8
length of the byte-substring [1,1] of `"ä"` -- note that since `"ä"` is wide,
this byte-substring is not valid UTF8). The PR code returns an error (because
the byte-substring is not valid UTF8), but Lua 5.3 returns `1`.

Looking at Lua's source code (from the file you cited), the specification is:
```
utf8len(s [, i [, j]]) --> number of characters that start in the
range [i,j], or nil + current position if 's' is not well formed in
that interval
```
To me, this doesn't sound completely define what should happen with `utf8len("ä",1,1)`. Also, it seems to me that the obvious way to get Lua's behavior is to backtrack from position `j` (or to move forward from position `i` until we're at or beyond `j`) and check individual UTF8 characters. (This is basically what the Lua code does. But in our situation, since we already have `glib` functions, I find this a bit ugly.)

What should we do here? Have an inconsistency with Lua 5.3 (in a somewhat exotic corner case), or imitate Lua 5.3 at the cost of a cumbersome implementation?

2017-09-29 05:27 UTC, aidanholm commented
The spec comment you cite says "number of characters that _start_ in the range [i,j]. For that example, the range covers the first byte of "ä", so there is no inconsistency there in the 5.3 code/spec. The docs are a little ambiguous regarding the error condition; they should read "If any invalid byte sequence _beginning in the range specified by [i,j]_ is found"

I'd prefer to be compatible with Lua 5.3 here. You could use `g_utf8_find_next_char` on the last byte in the range [i,j] to increase `bend` to include any partial character at the end of the string. Then validate the possibly expanded range with `g_utf8_validate`.

2017-09-29 05:41 UTC, aidanholm requested changes

2017-09-29 05:41 UTC, aidanholm commented on common/clib/utf8.c
> +    ssize_t blen;
Should be `size_t`, not `ssize_t`

2017-09-29 05:41 UTC, aidanholm commented on common/clib/utf8.c
> +    ssize_t bbeg, bend;
ditto

2017-09-29 05:41 UTC, aidanholm commented on common/clib/utf8.c
> +    luaL_argcheck(L, bend != -1, 3, "final position out of string");
`bend < bbeg` is also an error condition in 5.3

2017-09-29 05:41 UTC, aidanholm commented on common/clib/utf8.c
> +    if(!g_utf8_validate(str + bbeg, bend - bbeg, (const gchar **) &valend)) {
`valend` should be defined where it is used

2017-09-29 05:41 UTC, aidanholm commented on common/clib/utf8.c
> +    ssize_t blen;
`size_t`

2017-09-29 05:41 UTC, aidanholm commented on common/clib/utf8.c
> +    if(offset > 0)
There should be a space between `if` and `(`

2017-09-29 05:41 UTC, aidanholm commented on doc/luadoc/utf8.lua
> +-- @tparam string string The string whose length is to be returned.
This should include:
- information on the optional parameters
- longer description of how the function works, error conditions
- a "compatible with lua 5.3 utf8.len" comment

2017-09-29 05:41 UTC, aidanholm commented on doc/luadoc/utf8.lua
> +-- Convert an offset (in UTF8 characters) to a byte offset.
ditto

2017-09-29 05:41 UTC, aidanholm commented on tests/async/test_clib_utf8.lua
> +    assert.equal(2, utf8.len("äa", 1, 3))
Looks good! Will also need the `utf8.len("ä", 1, 1)` test case here too

2017-09-29 14:46 UTC, hofheinz commented on common/clib/utf8.c
> +    ssize_t blen;
`bbeg` and `bend` are currently signed because `luaH_utf8_convert_offset` may return a `-1` as an error indicator. This means having `blen` should also be `ssize_t` because we compare `bend` with `blen` at some point. Alternative: explicit type casts, or have `luaH_utf8_convert_offset` do something else in case of out-of-bounds errors. Not sure what to do (but I do like the concept of a helper function that converts negative to positive offsets and does out-of-bounds checks).

2017-09-29 14:49 UTC, hofheinz commented on common/clib/utf8.c
> +    luaL_argcheck(L, bend != -1, 3, "final position out of string");
I couldn't reproduce this. Running `lua53 -e 'print(utf8.len("abc",2,1))'` yields `0`. (`lua53 -v` yields `Lua 5.3.4  Copyright (C) 1994-2017 Lua.org, PUC-Rio`, this seems up to date.) Do you get different results?

2017-09-29 15:42 UTC, aidanholm commented on common/clib/utf8.c
> +    luaL_argcheck(L, bend != -1, 3, "final position out of string");
Sorry, I misread the Lua code for `utflen()`; the actual correct behavior is to return 0 if j < i, but I think your code handles this correctly already.

2017-09-29 15:50 UTC, aidanholm commented on common/clib/utf8.c
> +    ssize_t blen;
Unsigned overflow is well-defined; just return and compare against `(size_t)-1`. The other alternative is to pass in `L` and throw an error from the helper function, but that seems messier.

2017-09-29 15:51 UTC, aidanholm commented on common/clib/utf8.c
> +    bbeg = luaH_utf8_convert_offset(bbeg, blen);
I think the helper function should have a short name, so you can one-line these; something like `abspos`

2017-09-29 17:52 UTC, hofheinz commented
Thanks for the hints! (Your `g_utf8_find_next_char` suggestion worked nicely!) This is not finished yet, though, one of the corner cases tests is still failing. (Will get back to this.)

2017-09-29 18:10 UTC, hofheinz commented
Ok, tests pass now.

2017-10-01 14:57 UTC, aidanholm commented
Looks pretty good! I'll pull this, do some last fixups, and then manually merge it

2017-10-01 15:24 UTC, aidanholm commented
Merged at 3692d295; thanks for your work!

2017-10-01 15:24 UTC, closed without merging

2017-10-02 07:55 UTC, hofheinz commented
Great! Thanks for your comments, I learned a lot.

2017-10-02 11:57 UTC, aidanholm commented
Glad to hear :)