Update README with config for HiDPI
luakit/luakit pull request #545
Opened 2017-09-25 16:08 UTC by IWriteThings

Adds configuration instructions for HiDPI monitors.

2017-09-25 16:08 UTC, IWriteThings commented
This would close ticket #542 . Please review this change for acceptability.

2017-09-25 16:24 UTC, aidanholm requested changes
Thanks for the PR! Just a few minor suggestions really

2017-09-25 16:24 UTC, aidanholm commented on README.md
> +If you have a HiDPI monitor (> 1920x1080p) and need to increase the size of the font loaded, you can do so by changing the webview.zoom_level on the settings page (luakit://settings/) to 150 or 200 a
- I'd prefer if this long line were wrapped to a reasonable column length.
- `1920x1080p` -> `1920x1080`
- "and need to increase the size of the font loaded" -> "and find that web pages are too small"; technically this setting changes more than just the font size
- `webview.zoom_level` should be surrounded with backticks so that it renders in monospace.

2017-09-25 20:00 UTC, IWriteThings commented
I have updated the commits. Can you please review? I believe this meets all requests.

2017-09-26 03:42 UTC, aidanholm commented
Merged! Thanks :)

2017-09-26 03:42 UTC, closed without merging