Add function to simulate keystrokes.
luakit/luakit pull request #597
Opened 2017-11-16 10:22 UTC by amosbird

This patch is a rebase of the keysym branches, with some improvements and tenderly care of @aidanholm :)

2017-11-16 11:03 UTC, aidanholm requested changes

2017-11-16 11:03 UTC, aidanholm commented on lib/keysym.lua
> +--- Keysym for luakit.
I'm not happy with the name; should be "sendkeys" or "fakekeys" or something, but "keysym" is totally opaque

2017-11-16 11:03 UTC, aidanholm commented on lib/keysym.lua
> +-- Simulating keystrokes
remove extra line "Simulating keystrokes" here

2017-11-16 11:03 UTC, aidanholm commented on lib/keysym.lua
> +--  <code>keysym.send(w, "<S-Home><BackSpace>")</code>
indent code with four spaces instead of using `<code>`

2017-11-16 11:03 UTC, aidanholm commented on lib/keysym.lua
> +                w:error("bad keystring: " .. keystring)
- these are script errors, not user-facing error messages: use `error()` instead
- error message needs to say what's wrong with the keystring

a better version would be `error("keystring '" .. keystring .. "' contains empty modifier group")`; note the string concatenation; unfortunately `error()` doesn't support format strings (might hack that in at some point..)

2017-11-16 11:03 UTC, aidanholm commented on lib/keysym.lua
> +                w:error("bad modifier in keystring: " .. symbol)
ditto

2017-11-16 11:03 UTC, aidanholm commented on lib/keysym.lua
> +        w:error("bad keystring: " .. keystring)
ditto

2017-11-16 11:03 UTC, aidanholm commented on lib/keysym.lua
> +            w:error("failed to send keystroke: " .. key.key)
ditto

2017-11-16 11:03 UTC, aidanholm commented on lib/window.lua
> +        w.win:add_signal("key-press", function (_, mods, key, send)
`send` should be `synthetic`

2017-11-16 11:03 UTC, aidanholm commented on lib/window.lua
> +            if send then
this should be all one line; but the real problem is that this breaks people using external tools to automate luakit (is this likely? no, but it's still an API break)

I think the best solution for now is to add a `window.act_on_synthetic_keys` setting (feel free to think of a nicer name), and add it to the if-condition.

2017-11-16 11:03 UTC, aidanholm commented on widgets/common.c
> +    lua_pushboolean(L, ev->send_event);
:+1:

2017-11-16 11:03 UTC, aidanholm commented on widgets/window.c
> +    while(lua_next(L, 3)) {
I'm not happy with this bind syntax being different to the bind syntax used for keybindings. It might be a bit of work unifying that, but I'd also rather not get locked into having two syntaxes for compatibility reasons...

2017-11-16 11:03 UTC, aidanholm commented on widgets/window.c
> +    if (!gdk_keymap_get_entries_for_keyval(gdk_keymap_get_default(), keyval, &keys, &n_keys)) {
`gdk_keymap_get_default()` should be `NULL`

2017-11-16 11:03 UTC, aidanholm commented on widgets/window.c
> +    g_assert(keys);
can probably get rid of this as well

2017-11-16 11:03 UTC, aidanholm commented on widgets/window.c
> +    gdk_event_put(event);
I'd say move this `gdk_event_put()` call up against the `event_key` block above

2017-11-16 11:03 UTC, aidanholm commented on widgets/window.c
> +luaH_window_send_key(lua_State *L)
I haven't really looked at this code, but it's spamming warnings and that's a no no
```
Gdk-WARNING **: Event with type 8 not holding a GdkDevice. It is most likely synthesized outside Gdk/GTK+
```

2017-11-16 11:03 UTC, aidanholm commented on widgets/window.c
> +luaH_window_send_key(lua_State *L)
Also, in general this could do with some logging: probably just a `debug("sending key '%s' to window %p", ...)` is sufficient. And the validation should use `luaL_error()` on failure: this is a function that only fails if the user screwed up the argument.

2017-11-16 11:03 UTC, aidanholm commented on config/rc.lua
> +-- Add ability to send keystrokes to the window
Do we want this enabled by default? I'm undecided...

2017-11-16 11:03 UTC, aidanholm commented on lib/keysym.lua
> +    for char in string.gmatch(keystring, "[%z\1-\x7F\xC2-\xF4][\x80-\xBF]*") do
as mentioned on IRC, ugh; I'll have a look at getting `utf8.codes` in

2017-11-16 11:16 UTC, aidanholm commented
In addition, there are two test failures:
```
FAIL style/test_source_format / test_vim_modeline
  tests/style/test_source_format.lua:41: Some files do not have modelines:
  lib/keysym.lua                                         Missing/malformed modeline
FAIL style/test_source_format / test_lua_module_functions_are_documented
  tests/style/test_source_format.lua:262: Some Lua modules have documentation issues:
  lib/keysym.lua:22                                      Undocumented export 'send'
```
The modeline is the `-- vim: et:sw=4:ts=8:sts=4:tw=80` thing that every file has. The new window `send_keys` method will need documenting too, but that's more of a final task.

2017-11-16 14:00 UTC, aidanholm commented
Oh, and another thing I'd prefer is if you could add your changes on top of the existing commits in the keysym branch, as that preserves history: both the reasoning behind each section of code, and the attribution to the original authors

2017-11-18 10:47 UTC, amosbird commented on widgets/window.c
> +    if (!gdk_keymap_get_entries_for_keyval(gdk_keymap_get_default(), keyval, &keys, &n_keys)) {
Doesn't work if I change it to `NULL`

2017-11-19 04:13 UTC, aidanholm reviewed
Just a few minor fixes needed

2017-11-19 04:13 UTC, aidanholm commented on lib/window.lua
> +        desc = "Whether or not to act on syntheic keys.",
At the moment this is just restating the setting name; it should be more descriptive, e.g: "Whether synthetic key events should activate key bindings. Synthetic key events have been generated by a program rather than a physical key press, such as those sent by `keysym.send()`."

2017-11-19 04:13 UTC, aidanholm commented on lib/keysym.lua
> +    for char in string.gmatch(keystring, utf8.charpattern) do
The usual style here is to use method access notation: `keystring:gmatch(utf8.charpattern)`

2017-11-19 04:13 UTC, aidanholm commented on lib/keysym.lua
> +    local symbol = nil
this needs assertions that `w` is a table and `keystring` is a string

2017-11-19 04:13 UTC, aidanholm commented on lib/keysym.lua
> +            if string.match(symbol, "^[Ss]hift$") or
ditto

2017-11-19 04:13 UTC, aidanholm commented on lib/keysym.lua
> +    assert(not symbol)
This needs an "unterminated symbol" message

2017-11-19 04:13 UTC, aidanholm commented on widgets/window.c
>      if (!keyval || keyval == GDK_KEY_VoidSymbol) {
No need for braces with a single line body

2017-11-19 04:13 UTC, aidanholm commented on widgets/window.c
> +    luaH_checktable(L, 3);
The checktable call should be moved to the top with the other argument checks

2017-11-19 04:13 UTC, aidanholm commented on widgets/window.c
> +    debug("sending key '%s' with modifier %d to window %p",
The window pointer printed should be the widget (`w`)

2017-11-19 04:45 UTC, aidanholm commented on widgets/window.c
> +    luaH_checktable(L, 3);
Actually, the table should be optional, but if there is a third argument it must be a table

2017-11-24 15:33 UTC, aidanholm commented on widgets/window.c
> +    luaH_checktable(L, 3);
This needs to be inside `if (lua_gettop(L) >= 3)`, as we want to allow leaving the table out.

2017-11-24 15:47 UTC, aidanholm requested changes
more minor changes needed: mostly code style and documentation

2017-11-24 15:47 UTC, aidanholm commented on widgets/window.c
> +    luaH_checktable(L, 3);
This needs to be inside `if (lua_gettop(L) >= 3)`, as we want to allow leaving the table out.

2017-11-24 15:47 UTC, aidanholm commented on widgets/window.c
> +        return luaL_error(L, "key name isn't a utf-8 string.");
no full stop on error messages

2017-11-24 15:47 UTC, aidanholm commented on widgets/window.c
> +    luaH_checktable(L, 3);
in order not to add another check below in the modifier loop, you could add an `else lua_newtable(L);` to that

2017-11-24 15:47 UTC, aidanholm commented on widgets/window.c
> +
no gap here

2017-11-24 15:47 UTC, aidanholm commented on widgets/window.c
> +    gdk_event_set_device(event, gdk_seat_get_keyboard(gdk_display_get_default_seat(gdk_display_get_default())));
super long line here; should wrap it at the least, or break it into a `GdkSeat *seat = ...` line above it.

2017-11-24 15:47 UTC, aidanholm commented on widgets/window.c
> +    GdkKeymapKey* keys = NULL;
\* goes next to the variable name: 'GdkKeymapKey *keys`

2017-11-24 15:47 UTC, aidanholm commented on widgets/window.c
> +    while(lua_next(L, 3)) {
space between `while` and `(`

2017-11-24 15:47 UTC, aidanholm commented on widgets/window.c
> +    return 1;
should be returning 0; this function doesn't return a lua value

2017-11-24 15:47 UTC, aidanholm commented on lib/keysym.lua
> +                return
no need for `return` here: `error()` unwinds the stack

2017-11-24 15:47 UTC, aidanholm commented on lib/keysym.lua
> +--- Send synthetic keys to given window.
This needs more documentation of what sending keys means, and what the keystring format is. Ideally, a few examples, involving tricky cases like sending `<` and `>` keys, keys with modifiers, unicode keys..

2017-11-24 15:47 UTC, aidanholm commented on widgets/window.c
> +luaH_window_send_key(lua_State *L)
this needs some documentation added to `doc/luadoc/widget.window.lua`; can be a modified version of the keysym documentation

2017-11-24 17:02 UTC, aidanholm requested changes
few more minor fixes needed

2017-11-24 17:02 UTC, aidanholm commented on widgets/window.c
> +    if (lua_gettop(L) >= 3) luaH_checktable(L, 3);
should have a newline after `if (...)` and `else`

2017-11-24 17:02 UTC, aidanholm commented on widgets/window.c
> +        return luaL_error(L, "failed to get key map entries.");
no fullstop here

2017-11-24 17:02 UTC, aidanholm commented on doc/luadoc/widget.window.lua
> +-- Send synthetic keys to given window. This function parses a vim-like
s/synthetic keys/synthetic key events/

2017-11-24 17:02 UTC, aidanholm commented on doc/luadoc/widget.window.lua
> +-- `window.act_on_synthetic_keys` is on, synthetic key events will not trigger
s/on/disabled/

2017-11-24 17:02 UTC, aidanholm commented on lib/keysym.lua
> +-- When `window.act_on_synthetic_keys` is on, synthetic key events will
s/on/disabled/ here as well

2017-11-24 17:45 UTC, aidanholm commented on widgets/window.c
> +        return luaL_error(L, "cannot type '%s' on current keyboard layout",
need to free `state_string` here as well, otherwise we leak memory

2017-11-24 17:53 UTC, merged