show links to all luakit:// pages in the help page
luakit/luakit pull request #639
Opened 2017-12-31 02:48 UTC by jerojasro

Hello,

I've re-installed luakit, and spent quite a good time trying to figure how to configure it. I changed the documentation so it shows all the available chrome pages, so others don't have to dig that much to get to the config. facilities/new features available.

It's been a while since I wrote Lua; sorry for the lack of style.

Now the help page looks like this: https://imgur.com/rNt0fuV

2017-12-31 07:56 UTC, aidanholm requested changes
Thanks, this looks great! Just some minor changes needed

2017-12-31 07:56 UTC, aidanholm commented on lib/help_chrome.lua
> +    for _, v in pairs(chrome.available_handlers()) do
should use `ipairs` instead of `pairs`

2017-12-31 07:56 UTC, aidanholm commented on lib/chrome.lua
> +function _M.available_handlers()
This function needs a documentation comment

2017-12-31 15:14 UTC, jerojasro commented
Thanks for checking. I've implemented the changes you suggested.

2018-01-01 08:07 UTC, aidanholm requested changes
- Minor nit about documentation
- Please squash your fixup commits into the appropriate feature commit: the `ipairs` fixup would go into "show list of all available luakit:// pages in help page", and the doc fixup would go into the "chrome functionality one", producing two commits

Thanks!

2018-01-01 08:07 UTC, aidanholm commented on lib/chrome.lua
> +--- Returns the currently registered luakit:// handlers, as an array of strings.
- Minor quibble about phrasing, and also needs a `@treturn` line:
```
--- Retrieve a list of the currently registered luakit:// handlers.
-- @treturn {string} A list of `luakit://` handler names, in alpabetical order.
```

2018-01-01 21:15 UTC, jerojasro commented
I've added the suggested changes and force-pushed them; I'll try to keep in mind that rebasing is OK in this project :)

2018-01-04 03:19 UTC, merged

2018-01-04 03:23 UTC, aidanholm commented
Looks great, thanks!

Generally when you submit a PR (to any project), you do your work in a feature branch, and rebasing is fine because your branch is still separate from the main history, so nothing depends on it yet. In fact, rebasing is usually preferred, otherwise you end up with one or two meaningful commits and several fixups on top that clutter history. It's only once your work is merged that rebasing becomes a bad idea.

2018-01-12 11:33 UTC, McSinyx commented
I'm sorry if it's not supposed to be asked here, but why is `luakit://` chosen over `about:` in the first place?

2018-01-12 11:34 UTC, McSinyx commented
I'm sorry if it's not supposed to be asked here, but why was `luakit://` chosen over `about:` in the first place?

2018-01-12 14:39 UTC, aidanholm commented
Not a problem. That was before my time, but it may have been because webkit already uses the `about:` scheme.