export history_prev/next key binding options in cmdhist.
luakit/luakit pull request #641
Opened 2018-01-01 12:19 UTC by amosbird

2018-01-04 19:32 UTC, aidanholm reviewed
This approach won't quite work. The values will be evaluated at module load and stored into the local `hist_binds`, so by the time you've finished loading the module it's already too late to set them!

I'd move the functions into `local history_prev_func = ...`, etc, then add a small local table `{{_M.history_prev, history_prev_func}, ... }` when the bindings are added.

2018-01-08 16:09 UTC, aidanholm requested changes

2018-01-08 16:09 UTC, aidanholm commented on lib/cmdhist.lua
> +_M.history_prev = "<Up>"
These need documentation comments, but other than that everything looks perfect

2018-01-08 16:29 UTC, amosbird commented on lib/cmdhist.lua
> +_M.history_prev = "<Up>"
done

2018-01-08 16:35 UTC, merged