Improve mechanism of opening selection contents
luakit/luakit pull request #646
Opened 2018-01-05 10:54 UTC by McSinyx

Fixes #642.

Although `lousy.uri.split` is only used in `binds`, I keep it in `lousy.uri` to allow users to use it in their config (e.g. `:open` with `pp` mechanism).

2018-01-05 16:50 UTC, McSinyx commented
Wait a minute, should `pt` and `PT` have the same behavior as well?

2018-01-08 15:00 UTC, McSinyx commented
@aidanholm Could you please take a look at this PR :bowing_man:? I've been quite nervous for the last few days as I'm still very new in real-life software development.

2018-01-08 15:49 UTC, aidanholm requested changes
Hi @McSinyx, sorry for the delay! This looks mostly good, but there are a few changes needed.

`tests/async/test_lib_lousy_uri.lua` is also failing and needs to be edited, but that should be easy.

Also, it'd be great if you could write some small tests for `lousy.uri.is_uri` and `lousy.uri.split` (also in tests/async/test_lib_lousy_uri.lua)

2018-01-08 15:49 UTC, aidanholm commented on lib/binds.lua
> +    { "^pp$", [[Open URLs based on the current primary selection contents in the current tab.]],
There should be no need to add ^ and $ to the pattern. Same for all the other patterns.

2018-01-08 15:49 UTC, aidanholm commented on lib/lousy/uri.lua
> +    -- Navigate if the string contains . or /; or if it is a javascript-uri
1) Don't need the comment; it's obvious what the code does
2) I realise the old code was like this, but is . or /  a good heuristic? I can think of search terms that might include a . Maybe use `lousy.uri.parse`? (That doesn't work for about:blank or javascript: uris IIRC, which is why we need a separate `is_uri` function)

2018-01-08 15:49 UTC, aidanholm commented on lib/window.lua
> +        if not arg or arg:match("^%s*$") then return settings.get_setting("window.new_tab_page") end
This change is not relevant, so it shouldn't be included in the commit.

2018-01-08 15:49 UTC, aidanholm commented on lib/lousy/uri.lua
> +    local get_setting = require("settings").get_setting
I don't think that this function should add the search engine at all. Inserting the search engine at the beginning of search terms is specific to opening a bunch of split URIs/search terms, but is _not_ specific to the splitting itself.

I.e. search engines should be handled by the bindings.

2018-01-08 15:49 UTC, aidanholm commented on lib/binds.lua
> +            i, uri = next(uris)
This needs `local` in front, as do all the other bits of similar code in the other bindings.

2018-01-09 02:41 UTC, McSinyx commented on lib/binds.lua
> +    { "^pp$", [[Open URLs based on the current primary selection contents in the current tab.]],
Thank you, I tried to uniform the format from `*` to `^*$` while it was supposed to be the opposite way.

2018-01-09 02:42 UTC, McSinyx commented on lib/binds.lua
> +            i, uri = next(uris)
Oops, I haven't got used to Lua strict scopes yet.

2018-01-09 02:53 UTC, McSinyx commented on lib/lousy/uri.lua
> +    -- Navigate if the string contains . or /; or if it is a javascript-uri
2. Most search engines doesn't support symbol, except Symbol Hound. Well, that is the point: we always try to be too smart, but the function is too guess any way, and search can  always be enforced by user using `:open google search-string`. In addition, the problem in the logic here is that we need to grep URI outta articles, so URIs are not always  surrounded be whitespaces (i.e. followed by comma, period or in side brackets). Maybe I'll add *pseudo* to the function name, but it's already in `lousy` anyway.

2018-01-09 02:57 UTC, McSinyx commented on lib/lousy/uri.lua
> +    local get_setting = require("settings").get_setting
That's a good point, although `is_url` will need to be called again in bindings (which IMHO doesn't affect performance much).

2018-01-09 02:58 UTC, McSinyx commented on lib/window.lua
> +        if not arg or arg:match("^%s*$") then return settings.get_setting("window.new_tab_page") end
This is because I removed [L584](https://github.com/luakit/luakit/pull/646/files/777ff664390e2c0321fd1ff7d188750da82421ca#diff-ee6e38c430e943fe52665d5cc6002dafL584), hope it doesn't create too much noise.

2018-01-09 02:59 UTC, McSinyx commented
Thanks, I'll do the edits and create tests when I get home this afternoon.

2018-01-09 07:18 UTC, aidanholm commented on lib/binds.lua
> +            i, uri = next(uris)
Yeah, global-by-default is a bit of a pain, since you almost always have to use `local`, but it's necessary due to lua's lexical scoping.

2018-01-09 07:28 UTC, aidanholm commented on lib/lousy/uri.lua
> +    local get_setting = require("settings").get_setting
Should be fine: it would only an issue if someone had lots of hosts

2018-01-09 07:35 UTC, aidanholm commented on lib/lousy/uri.lua
> +    -- Navigate if the string contains . or /; or if it is a javascript-uri
Stripping junk like parens or commas from URIs belongs in `_M.split()`, although it'll make that function more complicated: probably something like this:
```lua
local junk = "([%.%{%}%,%[%]%<%>%;%:]*)"
local _, uri, _ = p:match("^"..junk..".-"..junk.."$")
if uri and _M.is_uri(uri) then ... elseif _M.is_uri(p) then ... else ... end
```

2018-01-09 14:38 UTC, aidanholm commented on lib/window.lua
> +        if not arg or arg:match("^%s*$") then return settings.get_setting("window.new_tab_page") end
It'd be better to change L584 to only remove `find` then. In this case, it's not terribly important, but the principle is that when you're trying to understand a line of code by using `git blame`, irrelevant changes make that take longer.

2018-01-11 15:40 UTC, McSinyx commented
I'm so sorry to say that it's now my turn to apologize for the delay, lately I've been quite busy on my undergrad application (tbh I'm worried af, and it feels good to put all those to a side and do something else less stressful like this).

There are a few things that I'm still having trouble on:

* Somehow `make` doesn't compile `tests/uri.c` (?)
* IMHO `lousy.util.is_uri` is alright now with these possible cases:
    * Full URI, e.g. `https://github.com`
    * W/o scheme, e.g. `debian.org`
    * File paths, e.g. `/home` or `Downloads/`
    * Local host, e.g. `localhost:8000`
* Brackets can be striped if they matches (I mean something similiar to `[(example.com)]`), but period and commas are, well, more problematic. Somehow trailing period is (semi-)legal (http://www.shareprice.co.uk/TW.) and comma can exist within the option part or the URL, so it can end the link as well.

2018-01-12 15:11 UTC, aidanholm requested changes

2018-01-12 15:11 UTC, aidanholm commented on lib/binds.lua
> +            local i, uri = next(uris)
split_uri returns an array (i.e. it has numeric keys from 1..n), so why not just check the length, and use a loop?
```lua
if #uris == 0 then w:notify("...") return end
for _, uri in ipairs(uris) do ... end
```

2018-01-12 15:11 UTC, aidanholm commented on lib/binds.lua
> +            w = window.new{is_uri(uri) and uri or w:search_open(engine .. uri)}
Same here: you can use `table.remove` to pull out the first URI to open the window with, and then a for loop over the rest

2018-01-12 15:11 UTC, aidanholm commented on lib/binds.lua
> +            local i, uri = next(uris)
ditto

2018-01-12 15:11 UTC, aidanholm commented on lib/binds.lua
> +            local i, uri = next(uris)
ditto

2018-01-12 15:11 UTC, aidanholm commented on lib/binds.lua
> +            local i, uri = next(uris)
ditto

2018-01-12 15:15 UTC, aidanholm commented
No worries; we all have limited time; good luck on your undergrad applications!

If there are compile errors, please post any error messages. I don't really have an opinion on how picky `is_uri` is: it's never going to be right 100% of the time. I do think that periods and commas should be stripped, as in my experience they're usually superfluous; and this only strips from the ends, not the middle, so it's easy to manually fix for the rare case where it's needed.

2018-01-13 15:18 UTC, McSinyx commented
Well, after running `make`, there still isn't `tests/util.so` so `run_test.lua` fail:

```sh
$ ./tests/run_test.lua luacheck
luajit: ./tests/run_test.lua:15: module 'tests.util' not found:
        no field package.preload['tests.util']
        no file './tests/util.lua'
        no file '/usr/share/luajit-2.1.0-beta3/tests/util.lua'
        no file '/usr/local/share/lua/5.1/tests/util.lua'
        no file '/usr/local/share/lua/5.1/tests/util/init.lua'
        no file '/usr/share/lua/5.1/tests/util.lua'
        no file '/usr/share/lua/5.1/tests/util/init.lua'
        no file './tests/tests/util.lua'
        no file './lib/tests/util.lua'
        no file './lib/tests/util/init.lua'
        no file './tests/util.so'
        no file '/usr/local/lib/lua/5.1/tests/util.so'
        no file '/usr/lib/i386-linux-gnu/lua/5.1/tests/util.so'
        no file '/usr/local/lib/lua/5.1/loadall.so'
        no file './tests.so'
        no file '/usr/local/lib/lua/5.1/tests.so'
        no file '/usr/lib/i386-linux-gnu/lua/5.1/tests.so'
        no file '/usr/local/lib/lua/5.1/loadall.so'
stack traceback:
        [C]: in function 'require'
        ./tests/run_test.lua:15: in main chunk
        [C]: at 0x0048b110
$ ls tests/
async  html  lib.lua  priv.lua  run_test.lua  style  util.c
```

2018-01-13 18:45 UTC, aidanholm commented
do you have `DEVELOPMENT_PATHS` set to 1 in your config.mk?

2018-01-14 00:24 UTC, McSinyx commented
:stuck_out_tongue: silly me, I haven't. But wait, there is still not `tests/util.so`. I guess I'll use the generated CFLAGS from `make` to compile it.

2018-01-14 10:48 UTC, McSinyx commented
I'm so sorry that I messed up the tree while rebasing :confused:

I've created PR #654 to replace this.

2018-01-14 10:48 UTC, closed without merging

2018-01-28 16:20 UTC, McSinyx commented
I'm back here just to say thank you @aidanholm for your blessing: I got accepted after the interview this morning.

2018-01-28 22:38 UTC, aidanholm commented
Congratulations!

2018-01-29 10:10 UTC, McSinyx commented
Thanks again man! It feels so relieving to be able to put away the worries.