Warning for deprecated config files (see #620).
luakit/luakit pull request #657
Opened 2018-01-14 16:09 UTC by zappathustra

This addresses #620.

Overloading `require()` might not be a good idea, but this is a first draft. Also, I guess the warning could be reworded.

2018-01-17 20:26 UTC, aidanholm commented
Hm, I think I agree with you that it's not a good idea :) A better solution is to insert a function at the beginning of `package.loaders`, which is what `require` calls to load modules.

2018-01-18 11:29 UTC, zappathustra commented
Oh, yes, `package.loaders` is a much more sensible choice! I'll implement that. For the record, it's `package.searchers` since 5.2, so I'll do something like this:

```
local loaders = package.searchers or package.loaders
```

so there'll be no problem when (if) you move to more recent Lua versions.

2018-01-19 23:20 UTC, zappathustra commented
Note: this will warn if there exists a non-luakit lua module (say LFS) in the config dir. To make sure that we're only checking for the files in `$INSTALL_DIR/lib`, a more complicated scheme is required, but is it really useful?

I noticed also that `luakit.install_paths.(install|config)_dir` do not return `./(lib|config)` when `$DEVELOPMENT_PATHS` is 1. Is that normal? That makes those values rather unusable when running from source.

2018-03-11 18:34 UTC, aidanholm requested changes
Sorry for the long delay! :(

2018-03-11 18:34 UTC, aidanholm commented on config/rc.lua
> +-- Perhaps paranoid, but you never know.
I think this is probably a little too paranoid; ordinarily I'd appreciate such caution, but here luakit controls the initial searchers (we can modify them before loading `rc.lua` if the need arises), so they effectively form part of the luakit API. The other reason is that this is going in the default rc file, which should be kept as short as possible.

2018-03-11 18:34 UTC, aidanholm commented on config/rc.lua
> +local function deprecated_files (module)
for the sake of brevity, I'd actually prefer to see this made an anonymous function, like this:
```lua
table.insert(package.loaders, function (modname)
    ...
end)
```
I think just using `package.loaders` is fine; if compatibility ever becomes an issue, we can deal with it then.
Also, `module` is already a global (although it might be good to clear it before `rc.lua` runs...) and it's better not to shadow it; `modname` is the name the lua51 api docs use.

2018-03-11 18:34 UTC, aidanholm commented on config/rc.lua
> +-- Checks whether there exist module files in the local config dir and warns
I appreciate the extensive documentation but think this could be shortened a bit, as it's part of the `rc.lua` file:
"Check for lua configuration files that will never be loaded because that are shadowed by builtin modues."

2018-03-11 18:34 UTC, aidanholm commented on config/rc.lua
> +    if f ==  lf then
spacing

2018-03-12 21:36 UTC, zappathustra commented on config/rc.lua
> +-- Perhaps paranoid, but you never know.
What I found paranoid is the way I remove the function, not the removal itself (necessary otherwise `userconf.lua`, and files required in it, produce warnings). Is that what you mean too, so you'd rather do `table.remove(package.loaders, 2)` instead?

2018-03-13 17:19 UTC, merged

2018-03-13 17:21 UTC, aidanholm commented
Thanks! merged :)

2018-03-14 17:03 UTC, zappathustra commented
You did not include the `table.remove` line in your merge. So there is a warning when `userconf.lua` is loaded. Is that on purpose?

2018-03-15 13:17 UTC, aidanholm commented
That was an oversight on my part, but I've realized that the current implementation is not ideal. It warns for all local modules, but should only warn for modules that shadow a builtin module. I'll fix it up a bit in develop.

2018-03-15 13:36 UTC, aidanholm commented
Added at 817586d