added prevent_default handling for dom events
luakit/luakit pull request #661
Opened 2018-01-22 12:32 UTC by serg-kozhemyakin

dom event's callback function can set prevent_default to true for its argument and in this case after returning from callback webkit_dom_event_prevent_default will be called for this event.

2018-01-22 16:21 UTC, aidanholm requested changes

2018-01-22 16:21 UTC, aidanholm commented on extension/clib/dom_element.c
> +    if (lua_isboolean(L, -1)) {
Should probably be `if (lua_toboolean( ... ))`, which simplifies the code below

2018-01-23 06:31 UTC, serg-kozhemyakin commented on extension/clib/dom_element.c
> +    if (lua_isboolean(L, -1)) {
hm, if i changing
    lua_pushliteral(L, "prevent_default");
    lua_rawget(L, -2);
    if (lua_isboolean(L, -1)) {
        lua_pushboolean(L, true);
        if (lua_equal(L, -1, -2)) {
            webkit_dom_event_prevent_default(event);
        }
        lua_pop(L, 1);
    }
    lua_pop(L, 2);
to
    lua_pushliteral(L, "prevent_default");
    lua_rawget(L, -2);
    if (lua_toboolean(L, -1)) {
        webkit_dom_event_prevent_default(event);
        lua_pop(L, 1);
    }
    lua_pop(L, 1);
then webkit process starts crashing after any callback. probably lua_toboolean pops stack itself (don't found info about its behavior in lua doc)

2018-01-23 22:06 UTC, aidanholm commented on extension/clib/dom_element.c
> +    if (lua_isboolean(L, -1)) {
There shouldn't be a `lua_pop()` call inside the if-statement body.

Looks fine when that's fixed: pushliteral+rawget pushes the boolean, toboolean checks it, and the final pop removes it.

2018-01-24 06:28 UTC, serg-kozhemyakin commented
updated commit. and also simplified 'cancel' check as well. now looks working so far.

2018-01-24 16:11 UTC, aidanholm requested changes
just formatting changes needed

2018-01-24 16:11 UTC, aidanholm commented on extension/clib/dom_element.c
> +    if (lua_toboolean(L, -1)) {
no need for { } here

2018-01-24 16:11 UTC, aidanholm commented on extension/clib/dom_element.c
> +    if (lua_toboolean(L, -1)) {
ditto

2018-01-25 05:50 UTC, serg-kozhemyakin commented on extension/clib/dom_element.c
> +    if (lua_toboolean(L, -1)) {
updated

2018-01-28 22:36 UTC, merged