New functions for styles module
luakit/luakit pull request #709
Opened 2018-06-07 19:03 UTC by gleachkr

This adds:
1. live editing of user styles,
2. toggling of user styles, and
3. creation of a new user style for the current uri.

2018-06-07 19:06 UTC, gleachkr commented on lib/styles.lua
> +--- Watch the styles directory for changes and apply them immediately.
This is probably the most adventurous bit of the pull request. Suggestions welcome. It might be nice to have this function return the guard table, or a closure, rather than passing the table in, but for some reason neither of those approaches seem to play nicely with the callback in `luakit.spawn`.

2018-06-11 12:47 UTC, aidanholm commented on lib/styles.lua
> +--- Watch the styles directory for changes and apply them immediately.
I'm not too happy with polling, although in this case it's not too bad. I'd prefer to see use of GFileMonitor, but that would need to be wrapped to be usable from lua, which could be a fair amount of work.

2018-06-11 12:47 UTC, aidanholm commented on lib/styles.lua
> +                editor.edit(file,1,function() guard[1] = nil end)
spaces after commas

2018-06-11 14:25 UTC, gleachkr commented on lib/styles.lua
> +--- Watch the styles directory for changes and apply them immediately.
Yeah, polling is not ideal. It's sort of a trade-off between this or adding dependencies and/or complexity. It might also be possible to either pull in an off-the-shelf inotify wrapper for lua, or to avoid polling in the presence of something like inotifywatch (falling back on sleep in the case of absence), by adding a little logic to the spawned process. But I thought that the simplicity here might outweigh the inelegance.

2018-06-11 14:25 UTC, gleachkr commented on lib/styles.lua
> +                editor.edit(file,1,function() guard[1] = nil end)
Right, will fix.

2018-06-11 16:00 UTC, aidanholm commented on lib/styles.lua
> +--- Watch the styles directory for changes and apply them immediately.
Unfortunately inotify is not available on the BSDs, so that's why GFileMonitor would be needed as an abstraction.

Maintenance of all the semi-functional C wrappers is becoming enough of a burden that I'm thinking of simply requiring gobject introspection, which would permit accessing GFileMonitor directly from lua. I believe there are already reasonably-high quality wrappers for glib, gio, etc that provide lua-like APIs. But that's a fair bit of work as well.

I think I'll be satisfied with just polling for now, especially since it's not active all the time. If you want to add in something like inotifywatch that'd be welcome, as long as polling is present as a fallback.

2018-06-11 19:55 UTC, gleachkr commented on lib/styles.lua
> +--- Watch the styles directory for changes and apply them immediately.
OK, I've added the inotifywatch (or actually, inotifywait, which was a little more convenient). There's a ten-second timeout so that it cleans itself up after the editor or luakit exits.

2018-06-14 14:55 UTC, gleachkr commented on lib/styles.lua
> +--- Watch the styles directory for changes and apply them immediately.
simplified the bash command slightly, and en-quoted the path for bash.

2018-06-16 13:53 UTC, aidanholm commented on lib/styles.lua
> +--- Watch the styles directory for changes and apply them immediately.
Thanks for the fixes. I have exams coming up, and won't have time to give this further review for another two weeks or so, but overall it looks pretty good.

2018-06-16 14:05 UTC, gleachkr commented on lib/styles.lua
> +--- Watch the styles directory for changes and apply them immediately.
OK, sounds good. Thanks for the update. Good luck on your exams!

2018-07-23 02:27 UTC, aidanholm requested changes
One tiny nit, and then this is ready for merge!

2018-07-23 02:27 UTC, aidanholm commented on lib/styles.lua
> +    { ":styles-new", "Create new userstyle for this domain", _M.new_style},
the binding description needs a full stop

2018-07-23 15:39 UTC, gleachkr commented
OK, should be ready to go!

2018-07-23 16:25 UTC, merged

2018-07-23 16:26 UTC, aidanholm commented
Merged! Thanks, and sorry for the wait!