Updated Makefile so LIBDIR actually does something
luakit/luakit pull request #935
Opened 2021-07-01 14:47 UTC by Charadon

While packaging luakit for opensuse, I found it was a struggle to get the library to it's proper location (lib64) and after investigating, found that the LIBDIR variable is unused. So I went and fixed it so LIBDIR can actually do something.

2021-07-02 00:17 UTC, taobert reviewed
I may be off the mark, but as the default `LIBDIR` is "LIBDIR     ?= $(PREFIX)/lib/luakit", i would expect that these should have the "/luakit" removed from them.

2021-07-02 13:09 UTC, Charadon commented
> I may be off the mark, but as the default `LIBDIR` is "LIBDIR ?= $(PREFIX)/lib/luakit", i would expect that these should have the "/luakit" removed from them.

If you're refering to config.mk, I didn't even think about changing that, but it shouldn't be hard change. Want me to go ahead and change it?

2021-07-03 02:07 UTC, taobert commented
No, i'm sorry i wasn't clear.
Currently, `LIBDIR` is set in `config.mk` to `$(PREFIX)/lib/luakit`, but then (as you point out) is not used.
Instead, the value `$(PREFIX)/lib/luakit` is used directly, so currently, `luakit.so` is put in `$(DESTDIR)$(PREFIX)/lib/luakit/`.
Your change now installs to `$(DESTDIR)$(LIBDIR)/luakit`, which when `LIBDIR` is expanded becomes `$(DESTDIR)$(PREFIX)/lib/luakit/luakit/`, so there's an extra `luakit/` directory created.
I feel that you should instead create and install to `$(DESTDIR)$(LIBDIR)`, which would maintain the current behaviour (with the current defaults), and also allow people to set `LIBDIR` to omit the `luakit` subdirectory entirely if they so chose.

2021-07-03 16:45 UTC, Charadon commented
Okay, I updated the Makefile to do that

2021-07-04 00:38 UTC, taobert commented
Looking at the makefile, there's an `options:` clause, that should probably have LIBDIR added to it (since it now does something).

I should also mention that my opinions aren't necessarily requisite for PR inclusion, and that this will have to wait until a grown-up casts an eye over it before it's pulled.

2021-07-04 13:03 UTC, Charadon commented
Alright, added a LIBDIR echo under options. Now I guess we'll wait a see if this gets approved.

2021-07-04 14:50 UTC, c0dev0id requested changes

2021-07-04 14:50 UTC, c0dev0id commented on Makefile
> +	@echo "APPDIR       = $(LIBDIR)"
Copy paste error. This should be LIBDIR on the left side.

2021-07-18 15:02 UTC, merged

2021-07-18 15:02 UTC, c0dev0id commented
Looks good. Thank you!