Solaris fixes for build/install
luakit/luakit pull request #979
Opened 2022-01-06 09:30 UTC by pekdon

Small fixes to get luakit build and install on Solaris 10.

2022-01-06 10:18 UTC, c0dev0id reviewed
comment moved to review.

2022-01-06 10:20 UTC, pekdon commented
That would just be expanded by the shell and passed to install as before so won't work unfortunately. :(

2022-01-06 10:26 UTC, c0dev0id requested changes

2022-01-06 10:26 UTC, c0dev0id commented on Makefile
> +	install -d $(DESTDIR)$(PREFIX)/share/luakit/lib/lousy/widget
This is actually not necessary. `install -d` creates missing components. So only the longest patch needs to be given.

2022-01-06 10:26 UTC, c0dev0id commented on build-utils/getversion.sh
> +    VERSION_FROM_GIT=`git describe --tags --always`
I'm not a fan - but I know the stone age sh in solaris demands it.
Does one of these work?
```
VERSION_FROM_GIT != "git describe --tags --always"
VERSION_FROM_GIT = $(shell git describe --tags --always)
```
I'd prefer !=

2022-01-06 10:26 UTC, c0dev0id commented on Makefile
> +	install -d $(DESTDIR)$(DOCDIR)/pages
Can you try if this works on solaris?
`install -d $(DESTDIR)$(DOCDIR)/{classes,modules,pages}`

2022-01-06 10:27 UTC, c0dev0id commented on Makefile
> +	install -d $(DESTDIR)$(PREFIX)/share/luakit/lib/lousy/widget
Ok, due to shell expansion. Of course.

2022-01-06 10:28 UTC, c0dev0id commented on Makefile
> +	install -d $(DESTDIR)$(DOCDIR)/pages
As per your comment earlier - this would not work. I'm ok with this.

2022-01-06 14:55 UTC, pekdon commented on Makefile
> +	install -d $(DESTDIR)$(PREFIX)/share/luakit/lib/lousy/widget
Yeah, I noticed that while doing the change but kept it as is. I'll drop the extra install.

2022-01-06 14:59 UTC, pekdon commented on build-utils/getversion.sh
> +    VERSION_FROM_GIT=`git describe --tags --always`
That's Makefile syntax, is it not? And no, does not work, not even with bash.

2022-01-06 22:55 UTC, taobert commented on Makefile
> -	install -d $(DESTDIR)$(PREFIX)/share/luakit/
I'm cautious about deleting this, as it may diminish futureproofness and hackability.
As has been mentioned in other comments, `install -d` will make any required parent directories,
so the following `install -d $(DESTDIR)$(DOCDIR)/classes` will create `$(DESTDIR)$(PREFIX)/share/luakit/`,
but only because `DOCDIR` is _by default_ `$(PREFIX)/share/luakit/doc`.
If a user decides for whatever reason that they want docs elsewhere, the rest of the install should carry on as normal.

2022-01-06 23:28 UTC, taobert commented on Makefile
> -	install -d $(DESTDIR)$(PREFIX)/share/luakit/
Hrmm. Well, looking harder, even if `DOCDIR` changes, `$(DESTDIR)$(PREFIX)/share/luakit/` will be created before it's needed by `install -d $(DESTDIR)$(PREFIX)/share/luakit/lib/lousy/widget` below. So sorry for the noise i guess.

2022-01-06 23:51 UTC, taobert reviewed
While i have no particular objection to for loops, i'm curious whether the failure of the current find(s) is due solely to solaris' sh requiring backticks rather than `$(...)`. Does
```
find resources -type f -exec sh -c 'f="{}"; install -m644 "$$f" "$(DESTDIR)$(PREFIX)/share/luakit/`dirname $$f`"' \;
 ```
work?

2022-01-07 07:27 UTC, pekdon commented
> While i have no particular objection to for loops, i'm curious whether the failure of the current find(s) is due solely to solaris' sh requiring backticks rather than `$(...)`. Does
> 
> ```
> find resources -type f -exec sh -c 'f="{}"; install -m644 "$$f" "$(DESTDIR)$(PREFIX)/share/luakit/`dirname $$f`"' \;
> ```
> 
> work?

Unfortunately not, I'm actually not sure how to trick find into parsing {} there as what happens is that f gets set to {} literal and not the current path.

```
# works
-exec echo '{}' \;
# prints {}
-exec echo "'{}'" \;
# prints {}
-exec echo '"{}"' \;
```

2022-01-07 07:32 UTC, pekdon commented on Makefile
> -	install -d $(DESTDIR)$(PREFIX)/share/luakit/
Want me to re-add the "extra" install -d or keep them? As long as you reviewers agree I'll update to whatever you decide. :)

2022-01-07 11:27 UTC, c0dev0id commented on build-utils/getversion.sh
> +    VERSION_FROM_GIT=`git describe --tags --always`
Interesting. Both versions work here with gmake. != also with bsd make. Backticks are fine. Let's leave them in.

2022-01-08 04:48 UTC, taobert commented on Makefile
> -	install -d $(DESTDIR)$(PREFIX)/share/luakit/
Well i'm not someone you need to convince, i'm just sticking my nose in unnecessarily.

My comment above was (erroniously) trying to protect against breakage for users who redefine variables. 
I _do_ kinda feel that explicitly creating every directory which will be installed into is likely to reduce brittleness,
and it's my supposition that that's why we have (had) lines like 
```
install -d $(DESTDIR)$(PREFIX)/share/luakit/lib $(DESTDIR)$(PREFIX)/share/luakit/lib/lousy $(DESTDIR)$(PREFIX)/share/luakit/lib/lousy/widget
```
rather than just using the longest path. So if it were up to me (it's not), i'd leave them in. If there were good reasons for reducing the number of `install` invocations (i don't really see any) then i'd put in a comment drawing the readers attention to the fact that the implicitly created directories are required. In a perfect world nobody working on the code would need those cues, but we don't have one of those, and they don't do much harm. But, i don't see these changes actively breaking anything right now, so, ya-know, whatever.:)

2022-01-11 11:41 UTC, c0dev0id approved these changes

2022-01-11 11:52 UTC, c0dev0id commented
I'm merging this PR. I think it's fine functionality wise. We can still improve things afterwards.
Thanks @pekdon

2022-01-11 11:53 UTC, merged